### ISSUE TITLE
 Warning: Unknown: failed to open stream error

### ISSUE THREAD

**Issue by kamleshwebtech** [arion85/laravel-backend-frontend#2]
i have installed your laravel repository as you suggested in readme.md file but getting below error message while running project in browser:

Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required '/Applications/XAMPP/xamppfiles/htdocs/sites/laravelprojects/laravel-backend-frontend/Frontend/server.php' (include_path='.:') in Unknown on line 0

**Comment by arion85** [comment]
Hello. I've add small changes to server.php. You can try again.
